name: movie_app
description: "A movie app made with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.2.1
  flutter_bloc: ^8.1.4
  logger: ^2.1.0
  dio: ^5.4.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  equatable: ^2.0.5
  injectable: ^2.3.5
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bot_toast: ^4.1.3
  reactive_forms: ^16.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4

  flutter_lints: ^3.0.0
  injectable_generator: ^2.5.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  expandable_text: ^2.3.0
  intl: ^0.19.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
